## Split data

In [5]:
import os
#from sqlalchemy import create_engine

In [ ]:
file = '/path/to/csv/file'

In [ ]:
csv_database = create_engine('sqlite:///csv_database.db')

SyntaxError: invalid character in identifier (<ipython-input-3-d379216558ba>, line 2)

## File path

In [49]:
data_root = r"/media/batman/WD20 Ext <Movies>/ConnHack2018/Fresh"
fname = r"meters001-050-timestamps.csv.gz"
this_file = os.path.join(data_root,fname)
this_file

'/media/batman/WD20 Ext <Movies>/ConnHack2018/Fresh/meters001-050-timestamps.csv.gz'

## Out path

In [162]:
out_fname = r"meters001-050_resample15.hdf5"
out_file_path = os.path.join(data_root,out_fname)
out_file_path

'/media/batman/WD20 Ext <Movies>/ConnHack2018/Fresh/meters001-050_resample15.hdf5'

## Data frame iterator

In [140]:
# cols_to_keep = [0,1,2,3,7]
# column_names = ['METERID','TSTAMP','ENERGY','POWER_ALL','ENERGY_OUT',]
# parse_dates = ['TSTAMP']
# dtype={'METERID': np.int32, 
#        'ENERGY': np.int32,
#        'POWER_ALL': np.int32,
#        'ENERGY_OUT': np.int32,
#       }
# df_iter = pd.read_csv(this_file, 
#                         skiprows=0, 
#                         compression='gzip',
#                         chunksize=1000000, 
#                         usecols=cols_to_keep,
#                         delimiter=";",
#                         header=None,
#                         names = column_names,
#                       dtype=dtype,
#                      parse_dates=parse_dates,
#                      index_col=1,
#                      )

## DF Iterator definition

In [164]:
def get_df_iter():
    cols_to_keep = [0,1,2,3,7]
    column_names = ['METERID','TSTAMP','ENERGY','POWER_ALL','ENERGY_OUT',]
    parse_dates = ['TSTAMP']
    dtype={'METERID': np.int32, 
       'ENERGY': np.int32,
       'POWER_ALL': np.int32,
       'ENERGY_OUT': np.int32,
      }    
    df_iter = pd.read_csv(this_file, 
                            skiprows=0, 
                            compression='gzip',
                            chunksize=1000000, 
                            usecols=cols_to_keep,
                            delimiter=";",
                            header=None,
                            names = column_names,
                          dtype=dtype,
                         parse_dates=parse_dates,
                         index_col=1,
                         )
    return df_iter

## Loop over iterator

In [170]:
# Get iterator
df_iter = get_df_iter()
new_df = pd.DataFrame()
count = 0
for df in df_iter:
    chunk_df_15min = df.resample('15T').first()
    #chunk_df_30min = df.resample('30T').first()
    #chunk_df_hourly = df.resample('H').first()    
    this_df = chunk_df_15min
    #this_df = this_df.pipe(lambda x: x[x.METERID == 1])
    #print("chunk",i)
    new_df = pd.concat([new_df,chunk_df_15min])
    print("chunk",count, len(chunk_df_15min), 'rows added')
    #print("chunk",i, len(temp_df),'rows added')
    #break
    count += 1

chunk 0 58410 30min rows added
chunk 1 2223 30min rows added
chunk 2 2223 30min rows added
chunk 3 2227 30min rows added
chunk 4 2223 30min rows added
chunk 5 2224 30min rows added
chunk 6 2223 30min rows added
chunk 7 2223 30min rows added
chunk 8 2223 30min rows added
chunk 9 2223 30min rows added
chunk 10 2223 30min rows added
chunk 11 2223 30min rows added
chunk 12 2220 30min rows added
chunk 13 2223 30min rows added
chunk 14 2223 30min rows added
chunk 15 2223 30min rows added
chunk 16 2223 30min rows added
chunk 17 40288 30min rows added
chunk 18 2223 30min rows added
chunk 19 2223 30min rows added
chunk 20 2268 30min rows added
chunk 21 2227 30min rows added
chunk 22 2231 30min rows added
chunk 23 2366 30min rows added
chunk 24 2442 30min rows added
chunk 25 2642 30min rows added
chunk 26 2223 30min rows added
chunk 27 2275 30min rows added
chunk 28 2233 30min rows added
chunk 29 2223 30min rows added
chunk 30 2219 30min rows added
chunk 31 2223 30min rows added
chunk 32 2223 30min rows added
chunk 33 2223 30min rows added
chunk 34 2223 30min rows added
chunk 35 39131 30min rows added
chunk 36 24780 30min rows added
chunk 37 2230 30min rows added
chunk 38 2230 30min rows added
chunk 39 2228 30min rows added
chunk 40 2231 30min rows added
chunk 41 2230 30min rows added
chunk 42 2226 30min rows added
chunk 43 2238 30min rows added
chunk 44 2227 30min rows added
chunk 45 2281 30min rows added
chunk 46 3077 30min rows added
chunk 47 2225 30min rows added
chunk 48 2268 30min rows added
chunk 49 2230 30min rows added
chunk 50 2224 30min rows added
chunk 51 2224 30min rows added
chunk 52 2700 30min rows added
chunk 53 2223 30min rows added
chunk 54 2224 30min rows added
chunk 55 2224 30min rows added
chunk 56 2250 30min rows added
chunk 57 2246 30min rows added
chunk 58 2404 30min rows added
chunk 59 2469 30min rows added
chunk 60 2224 30min rows added
chunk 61 2224 30min rows added
chunk 62 2227 30min rows added
chunk 63 39701 30min rows added
chunk 64 2225 30min rows added
chunk 65 2225 30min rows added
chunk 66 2241 30min rows added
chunk 67 2242 30min rows added
chunk 68 2225 30min rows added
chunk 69 2227 30min rows added
chunk 70 2227 30min rows added
chunk 71 2225 30min rows added
chunk 72 2225 30min rows added
chunk 73 2230 30min rows added
chunk 74 2254 30min rows added
chunk 75 2311 30min rows added
chunk 76 2303 30min rows added
chunk 77 2302 30min rows added
chunk 78 2341 30min rows added
chunk 79 2228 30min rows added
chunk 80 2225 30min rows added
chunk 81 97104 30min rows added
chunk 82 2227 30min rows added
chunk 83 2228 30min rows added
chunk 84 2230 30min rows added
chunk 85 2228 30min rows added
chunk 86 2229 30min rows added
chunk 87 2229 30min rows added
chunk 88 5442 30min rows added
chunk 89 4160 30min rows added
chunk 90 2416 30min rows added
chunk 91 2253 30min rows added
chunk 92 2229 30min rows added
chunk 93 2225 30min rows added
chunk 94 5189 30min rows added
chunk 95 2225 30min rows added
chunk 96 7959 30min rows added
chunk 97 2223 30min rows added
chunk 98 2223 30min rows added
chunk 99 14695 30min rows added
chunk 100 2223 30min rows added
chunk 101 2223 30min rows added
chunk 102 2223 30min rows added
chunk 103 2225 30min rows added
chunk 104 2223 30min rows added
chunk 105 2223 30min rows added
chunk 106 2224 30min rows added
chunk 107 2219 30min rows added
chunk 108 2223 30min rows added
chunk 109 2224 30min rows added
chunk 110 2223 30min rows added
chunk 111 2223 30min rows added
chunk 112 34897 30min rows added
chunk 113 2223 30min rows added
chunk 114 2228 30min rows added
chunk 115 2223 30min rows added
chunk 116 2223 30min rows added
chunk 117 2223 30min rows added
chunk 118 2224 30min rows added
chunk 119 2223 30min rows added
chunk 120 2223 30min rows added
chunk 121 2223 30min rows added
chunk 122 2223 30min rows added
chunk 123 2220 30min rows added
chunk 124 2223 30min rows added
chunk 125 2223 30min rows added
chunk 126 2223 30min rows added
chunk 127 2223 30min rows added
chunk 128 41232 30min rows added
chunk 129 2224 30min rows added
chunk 130 2224 30min rows added
chunk 131 2226 30min rows added
chunk 132 2228 30min rows added
chunk 133 2226 30min rows added
chunk 134 2225 30min rows added
chunk 135 2226 30min rows added
chunk 136 2225 30min rows added
chunk 137 2226 30min rows added
chunk 138 2226 30min rows added
chunk 139 2224 30min rows added
chunk 140 2224 30min rows added
chunk 141 2223 30min rows added
chunk 142 2220 30min rows added
chunk 143 2223 30min rows added
chunk 144 2223 30min rows added
chunk 145 2223 30min rows added
chunk 146 32317 30min rows added
chunk 147 2227 30min rows added
chunk 148 2223 30min rows added
chunk 149 2223 30min rows added
chunk 150 2223 30min rows added
chunk 151 2224 30min rows added
chunk 152 2223 30min rows added
chunk 153 2223 30min rows added
chunk 154 2223 30min rows added
chunk 155 2223 30min rows added
chunk 156 2220 30min rows added
chunk 157 2223 30min rows added
chunk 158 2223 30min rows added
chunk 159 2223 30min rows added
chunk 160 2223 30min rows added
chunk 161 26919 30min rows added
chunk 162 2227 30min rows added
chunk 163 2322 30min rows added
chunk 164 2822 30min rows added
chunk 165 2233 30min rows added
chunk 166 2999 30min rows added
chunk 167 3599 30min rows added
chunk 168 2245 30min rows added
chunk 169 2804 30min rows added
chunk 170 2246 30min rows added
chunk 171 2250 30min rows added
chunk 172 42006 30min rows added
chunk 173 2223 30min rows added
chunk 174 2223 30min rows added
chunk 175 2223 30min rows added
chunk 176 2227 30min rows added
chunk 177 2223 30min rows added
chunk 178 2223 30min rows added
chunk 179 6412 30min rows added
chunk 180 3879 30min rows added
chunk 181 2224 30min rows added
chunk 182 2223 30min rows added
chunk 183 2223 30min rows added
chunk 184 2223 30min rows added
chunk 185 2224 30min rows added
chunk 186 2223 30min rows added
chunk 187 2223 30min rows added
chunk 188 2220 30min rows added
chunk 189 2223 30min rows added
chunk 190 2223 30min rows added
chunk 191 2223 30min rows added
chunk 192 2224 30min rows added
chunk 193 41624 30min rows added
chunk 194 2282 30min rows added
chunk 195 39708 30min rows added
chunk 196 2224 30min rows added
chunk 197 2223 30min rows added
chunk 198 2227 30min rows added
chunk 199 2223 30min rows added
chunk 200 2223 30min rows added
chunk 201 2224 30min rows added
chunk 202 2223 30min rows added
chunk 203 2223 30min rows added
chunk 204 2223 30min rows added
chunk 205 2223 30min rows added
chunk 206 2224 30min rows added
chunk 207 2223 30min rows added
chunk 208 2219 30min rows added
chunk 209 2223 30min rows added
chunk 210 2223 30min rows added
chunk 211 2223 30min rows added
chunk 212 2224 30min rows added
chunk 213 37557 30min rows added
chunk 214 2225 30min rows added
chunk 215 2231 30min rows added
chunk 216 2225 30min rows added
chunk 217 2225 30min rows added
chunk 218 2226 30min rows added
chunk 219 2225 30min rows added
chunk 220 2225 30min rows added
chunk 221 2226 30min rows added
chunk 222 2225 30min rows added
chunk 223 2225 30min rows added
chunk 224 2226 30min rows added
chunk 225 2221 30min rows added
chunk 226 2226 30min rows added
chunk 227 2225 30min rows added
chunk 228 2225 30min rows added
chunk 229 39691 30min rows added
chunk 230 2223 30min rows added
chunk 231 2236 30min rows added
chunk 232 2223 30min rows added
chunk 233 2227 30min rows added
chunk 234 2223 30min rows added
chunk 235 2223 30min rows added
chunk 236 2223 30min rows added
chunk 237 2224 30min rows added
chunk 238 2223 30min rows added
chunk 239 2223 30min rows added
chunk 240 2223 30min rows added
chunk 241 2223 30min rows added
chunk 242 2224 30min rows added
chunk 243 2219 30min rows added
chunk 244 2223 30min rows added
chunk 245 2223 30min rows added
chunk 246 2223 30min rows added
chunk 247 37749 30min rows added
chunk 248 2224 30min rows added
chunk 249 3322 30min rows added
chunk 250 2227 30min rows added
chunk 251 2224 30min rows added
chunk 252 2224 30min rows added
chunk 253 2224 30min rows added
chunk 254 2224 30min rows added
chunk 255 2224 30min rows added
chunk 256 2224 30min rows added
chunk 257 2223 30min rows added
chunk 258 2224 30min rows added
chunk 259 2220 30min rows added
chunk 260 2225 30min rows added
chunk 261 2223 30min rows added
chunk 262 2224 30min rows added
chunk 263 2224 30min rows added
chunk 264 41976 30min rows added
chunk 265 2326 30min rows added
chunk 266 2881 30min rows added
chunk 267 2714 30min rows added
chunk 268 2326 30min rows added
chunk 269 2425 30min rows added
chunk 270 16031 30min rows added
chunk 271 2897 30min rows added
chunk 272 4412 30min rows added
chunk 273 2383 30min rows added
chunk 274 14968 30min rows added
chunk 275 2226 30min rows added
chunk 276 2223 30min rows added
chunk 277 2224 30min rows added
chunk 278 22128 30min rows added
chunk 279 2224 30min rows added
chunk 280 8159 30min rows added
chunk 281 2221 30min rows added
chunk 282 2223 30min rows added
chunk 283 2231 30min rows added
chunk 284 2223 30min rows added
chunk 285 2224 30min rows added
chunk 286 38554 30min rows added
chunk 287 2223 30min rows added
chunk 288 2224 30min rows added
chunk 289 2227 30min rows added
chunk 290 2255 30min rows added
chunk 291 2226 30min rows added
chunk 292 2223 30min rows added
chunk 293 2223 30min rows added
chunk 294 2223 30min rows added
chunk 295 2224 30min rows added
chunk 296 2223 30min rows added
chunk 297 2223 30min rows added
chunk 298 2223 30min rows added
chunk 299 2222 30min rows added
chunk 300 2224 30min rows added
chunk 301 2223 30min rows added
chunk 302 2223 30min rows added
chunk 303 2223 30min rows added
chunk 304 40380 30min rows added
chunk 305 22431 30min rows added
chunk 306 2225 30min rows added
chunk 307 2224 30min rows added
chunk 308 2221 30min rows added
chunk 309 2224 30min rows added
chunk 310 2585 30min rows added
chunk 311 2225 30min rows added
chunk 312 36805 30min rows added
chunk 313 2223 30min rows added
chunk 314 2223 30min rows added
chunk 315 2227 30min rows added
chunk 316 2223 30min rows added
chunk 317 2223 30min rows added
chunk 318 2224 30min rows added
chunk 319 2223 30min rows added
chunk 320 2223 30min rows added
chunk 321 2223 30min rows added
chunk 322 2223 30min rows added
chunk 323 2223 30min rows added
chunk 324 2220 30min rows added
chunk 325 2223 30min rows added
chunk 326 2223 30min rows added
chunk 327 2223 30min rows added
chunk 328 2223 30min rows added
chunk 329 41226 30min rows added
chunk 330 2223 30min rows added
chunk 331 2223 30min rows added
chunk 332 2223 30min rows added
chunk 333 2227 30min rows added
chunk 334 2223 30min rows added
chunk 335 2223 30min rows added
chunk 336 2223 30min rows added
chunk 337 2223 30min rows added
chunk 338 2224 30min rows added
chunk 339 2223 30min rows added
chunk 340 2223 30min rows added
chunk 341 2223 30min rows added
chunk 342 2223 30min rows added
chunk 343 2219 30min rows added
chunk 344 2223 30min rows added
chunk 345 2223 30min rows added
chunk 346 2224 30min rows added
chunk 347 37591 30min rows added
chunk 348 2223 30min rows added
chunk 349 2224 30min rows added
chunk 350 2227 30min rows added
chunk 351 2223 30min rows added
chunk 352 2223 30min rows added
chunk 353 2223 30min rows added
chunk 354 2224 30min rows added
chunk 355 2223 30min rows added
chunk 356 2223 30min rows added
chunk 357 2223 30min rows added
chunk 358 2224 30min rows added
chunk 359 2219 30min rows added
chunk 360 2223 30min rows added
chunk 361 2223 30min rows added
chunk 362 2223 30min rows added
chunk 363 2223 30min rows added
chunk 364 37766 30min rows added
chunk 365 2223 30min rows added
chunk 366 2223 30min rows added
chunk 367 2227 30min rows added
chunk 368 2223 30min rows added
chunk 369 2223 30min rows added
chunk 370 2223 30min rows added
chunk 371 2224 30min rows added
chunk 372 2223 30min rows added
chunk 373 2223 30min rows added
chunk 374 2223 30min rows added
chunk 375 2223 30min rows added
chunk 376 7909 30min rows added
chunk 377 2224 30min rows added
chunk 378 2223 30min rows added
chunk 379 30292 30min rows added
chunk 380 3580 30min rows added
chunk 381 2223 30min rows added
chunk 382 3892 30min rows added
chunk 383 2669 30min rows added
chunk 384 2224 30min rows added
chunk 385 2278 30min rows added
chunk 386 2219 30min rows added
chunk 387 2223 30min rows added
chunk 388 2238 30min rows added
chunk 389 2226 30min rows added
chunk 390 2223 30min rows added
chunk 391 37764 30min rows added
chunk 392 2223 30min rows added
chunk 393 2223 30min rows added
chunk 394 2227 30min rows added
chunk 395 2223 30min rows added
chunk 396 2224 30min rows added
chunk 397 2223 30min rows added
chunk 398 7148 30min rows added
chunk 399 24367 30min rows added
chunk 400 2223 30min rows added
chunk 401 2224 30min rows added
chunk 402 2227 30min rows added
chunk 403 2223 30min rows added
chunk 404 2223 30min rows added
chunk 405 2223 30min rows added
chunk 406 2223 30min rows added
chunk 407 2224 30min rows added
chunk 408 2223 30min rows added
chunk 409 2223 30min rows added
chunk 410 2223 30min rows added
chunk 411 28574 30min rows added
chunk 412 2225 30min rows added
chunk 413 2320 30min rows added
chunk 414 2230 30min rows added
chunk 415 2229 30min rows added
chunk 416 2226 30min rows added
chunk 417 2227 30min rows added
chunk 418 2225 30min rows added
chunk 419 2225 30min rows added
chunk 420 2254 30min rows added
chunk 421 2225 30min rows added
chunk 422 2226 30min rows added
chunk 423 2225 30min rows added
chunk 424 2221 30min rows added
chunk 425 2226 30min rows added
chunk 426 2224 30min rows added
chunk 427 2225 30min rows added
chunk 428 2226 30min rows added
chunk 429 32197 30min rows added
chunk 430 2227 30min rows added
chunk 431 5063 30min rows added
chunk 432 2226 30min rows added
chunk 433 2223 30min rows added
chunk 434 2223 30min rows added
chunk 435 2224 30min rows added
chunk 436 2224 30min rows added
chunk 437 2223 30min rows added
chunk 438 2456 30min rows added
chunk 439 3643 30min rows added
chunk 440 2224 30min rows added
chunk 441 37952 30min rows added
chunk 442 2223 30min rows added
chunk 443 2223 30min rows added
chunk 444 2234 30min rows added
chunk 445 2223 30min rows added
chunk 446 2223 30min rows added
chunk 447 2224 30min rows added
chunk 448 2223 30min rows added
chunk 449 2225 30min rows added
chunk 450 2225 30min rows added
chunk 451 2224 30min rows added
chunk 452 2223 30min rows added
chunk 453 2223 30min rows added
chunk 454 2220 30min rows added
chunk 455 2224 30min rows added
chunk 456 2223 30min rows added
chunk 457 2223 30min rows added
chunk 458 33086 30min rows added
chunk 459 2227 30min rows added
chunk 460 2224 30min rows added
chunk 461 2223 30min rows added
chunk 462 2223 30min rows added
chunk 463 2223 30min rows added
chunk 464 2224 30min rows added
chunk 465 2223 30min rows added
chunk 466 2223 30min rows added
chunk 467 2223 30min rows added
chunk 468 2223 30min rows added
chunk 469 2220 30min rows added
chunk 470 2223 30min rows added
chunk 471 2223 30min rows added
chunk 472 2223 30min rows added
chunk 473 207109 30min rows added
chunk 474 2269 30min rows added
chunk 475 2256 30min rows added
chunk 476 2266 30min rows added
chunk 477 2662 30min rows added
chunk 478 2265 30min rows added
chunk 479 2250 30min rows added
chunk 480 2254 30min rows added
chunk 481 2254 30min rows added
chunk 482 2256 30min rows added
chunk 483 2258 30min rows added
chunk 484 2345 30min rows added
chunk 485 2414 30min rows added
chunk 486 2244 30min rows added
chunk 487 2248 30min rows added
chunk 488 2252 30min rows added
chunk 489 2261 30min rows added
chunk 490 2272 30min rows added
chunk 491 2276 30min rows added
chunk 492 2264 30min rows added
chunk 493 2274 30min rows added
chunk 494 2255 30min rows added
chunk 495 2251 30min rows added
chunk 496 2262 30min rows added
chunk 497 2256 30min rows added
chunk 498 2254 30min rows added
chunk 499 2251 30min rows added
chunk 500 2249 30min rows added
chunk 501 2248 30min rows added
chunk 502 2246 30min rows added
chunk 503 2257 30min rows added
chunk 504 2262 30min rows added
chunk 505 2266 30min rows added
chunk 506 2266 30min rows added
chunk 507 2265 30min rows added
chunk 508 2263 30min rows added
chunk 509 2253 30min rows added
chunk 510 2257 30min rows added
chunk 511 2266 30min rows added
chunk 512 2263 30min rows added
chunk 513 2259 30min rows added
chunk 514 2252 30min rows added
chunk 515 2277 30min rows added
chunk 516 2266 30min rows added
chunk 517 2248 30min rows added
chunk 518 2265 30min rows added
chunk 519 2314 30min rows added
chunk 520 2296 30min rows added
chunk 521 2265 30min rows added
chunk 522 2270 30min rows added
chunk 523 2273 30min rows added
chunk 524 2593 30min rows added
chunk 525 2260 30min rows added
chunk 526 2251 30min rows added
chunk 527 2290 30min rows added
chunk 528 2292 30min rows added
chunk 529 2258 30min rows added
chunk 530 2250 30min rows added
chunk 531 2249 30min rows added
chunk 532 2240 30min rows added
chunk 533 2263 30min rows added
chunk 534 2261 30min rows added
chunk 535 2268 30min rows added
chunk 536 2270 30min rows added
chunk 537 2267 30min rows added
chunk 538 2307 30min rows added
chunk 539 2278 30min rows added
chunk 540 2312 30min rows added
chunk 541 2274 30min rows added
chunk 542 2271 30min rows added
chunk 543 2271 30min rows added
chunk 544 2271 30min rows added
chunk 545 2257 30min rows added
chunk 546 2242 30min rows added
chunk 547 2239 30min rows added
chunk 548 2243 30min rows added
chunk 549 2264 30min rows added
chunk 550 2277 30min rows added
chunk 551 2280 30min rows added
chunk 552 2282 30min rows added
chunk 553 2262 30min rows added
chunk 554 2294 30min rows added
chunk 555 2388 30min rows added
chunk 556 2330 30min rows added
chunk 557 2322 30min rows added
chunk 558 2316 30min rows added
chunk 559 2303 30min rows added
chunk 560 2288 30min rows added
chunk 561 2262 30min rows added
chunk 562 2263 30min rows added
chunk 563 2305 30min rows added
chunk 564 20881 30min rows added
chunk 565 2223 30min rows added
chunk 566 2223 30min rows added
chunk 567 2223 30min rows added
chunk 568 2223 30min rows added
chunk 569 2221 30min rows added
chunk 570 2226 30min rows added
chunk 571 2223 30min rows added
chunk 572 2223 30min rows added
chunk 573 2223 30min rows added
chunk 574 37692 30min rows added
chunk 575 2223 30min rows added
chunk 576 2227 30min rows added
chunk 577 2223 30min rows added
chunk 578 2223 30min rows added
chunk 579 2224 30min rows added
chunk 580 2223 30min rows added
chunk 581 2223 30min rows added
chunk 582 2223 30min rows added
chunk 583 2223 30min rows added
chunk 584 2225 30min rows added
chunk 585 2223 30min rows added
chunk 586 2219 30min rows added
chunk 587 2224 30min rows added
chunk 588 2223 30min rows added
chunk 589 2223 30min rows added
chunk 590 2223 30min rows added
chunk 591 39803 30min rows added
chunk 592 2223 30min rows added
chunk 593 2223 30min rows added
chunk 594 2227 30min rows added
chunk 595 2224 30min rows added
chunk 596 2223 30min rows added
chunk 597 2223 30min rows added
chunk 598 2223 30min rows added
chunk 599 2223 30min rows added
chunk 600 2224 30min rows added
chunk 601 20938 30min rows added
chunk 602 2223 30min rows added
chunk 603 2223 30min rows added
chunk 604 2227 30min rows added
chunk 605 2223 30min rows added
chunk 606 2224 30min rows added
chunk 607 2223 30min rows added
chunk 608 2223 30min rows added
chunk 609 2223 30min rows added
chunk 610 2223 30min rows added
chunk 611 2223 30min rows added
chunk 612 2224 30min rows added
chunk 613 2219 30min rows added
chunk 614 2223 30min rows added
chunk 615 2223 30min rows added
chunk 616 2223 30min rows added
chunk 617 2223 30min rows added
chunk 618 35746 30min rows added
chunk 619 2223 30min rows added
chunk 620 2228 30min rows added
chunk 621 2223 30min rows added
chunk 622 2223 30min rows added
chunk 623 2224 30min rows added
chunk 624 2224 30min rows added
chunk 625 2223 30min rows added
chunk 626 2223 30min rows added

In [171]:
new_df.to_hdf(out_file_path, key="test")

In [158]:
new_df

                     METERID        ENERGY  POWER_ALL  ENERGY_OUT
TSTAMP
2015-06-04 08:00:00      1.0 -4.949673e+08        0.0         0.0
2015-06-04 08:15:00      1.0 -2.404033e+08   289150.0         0.0
2015-06-04 08:30:00      NaN           NaN        NaN         NaN
2015-06-04 08:45:00      NaN           NaN        NaN         NaN
2015-06-04 09:00:00      NaN           NaN        NaN         NaN
2015-06-04 09:15:00      NaN           NaN        NaN         NaN
2015-06-04 09:30:00      NaN           NaN        NaN         NaN
2015-06-04 09:45:00      NaN           NaN        NaN         NaN
2015-06-04 10:00:00      NaN           NaN        NaN         NaN
2015-06-04 10:15:00      NaN           NaN        NaN         NaN
2015-06-04 10:30:00      NaN           NaN        NaN         NaN
2015-06-04 10:45:00      NaN           NaN        NaN         NaN
2015-06-04 11:00:00      NaN           NaN        NaN         NaN
2015-06-04 11:15:00      NaN           NaN        NaN         NaN
2015-06-04 11:30:00      NaN           NaN        NaN         NaN
2015-06-04 11:45:00      NaN           NaN        NaN         NaN
2015-06-04 12:00:00      NaN           NaN        NaN         NaN
2015-06-04 12:15:00      NaN           NaN        NaN         NaN
2015-06-04 12:30:00      NaN           NaN        NaN         NaN
2015-06-04 12:45:00      NaN           NaN        NaN         NaN
2015-06-04 13:00:00      NaN           NaN        NaN         NaN
2015-06-04 13:15:00      NaN           NaN        NaN         NaN
2015-06-04 13:30:00      NaN           NaN        NaN         NaN
2015-06-04 13:45:00      NaN           NaN        NaN         NaN
2015-06-04 14:00:00      NaN           NaN        NaN         NaN
2015-06-04 14:15:00      NaN           NaN        NaN         NaN
2015-06-04 14:30:00      NaN           NaN        NaN         NaN
2015-06-04 14:45:00      NaN           NaN        NaN         NaN
2015-06-04 15:00:00      NaN           NaN        NaN         NaN
2015-06-04 15:15:00      NaN           NaN        NaN         NaN
...                      ...           ...        ...         ...
2017-02-01 11:00:00      1.0 -1.748175e+09   252870.0         0.0
2017-02-01 11:15:00      1.0 -1.243934e+09   209370.0         0.0
2017-02-01 11:30:00      1.0 -2.867527e+08   309280.0         0.0
2017-02-01 11:45:00      1.0  3.848413e+08   287380.0         0.0
2017-02-01 12:00:00      1.0  5.891470e+08  2312530.0         0.0
2017-02-01 12:15:00      1.0 -1.702077e+09   436830.0         0.0
2017-02-01 12:30:00      1.0 -7.415683e+08   389150.0         0.0
2017-02-01 12:45:00      1.0  1.243197e+08   213470.0         0.0
2017-02-01 13:00:00      1.0  8.982647e+08   397110.0         0.0
2017-02-01 13:15:00      1.0  1.730482e+09   371380.0         0.0
2017-02-01 13:30:00      1.0 -1.740411e+09   376350.0         0.0
2017-02-01 13:45:00      1.0  6.900994e+08   364120.0         0.0
2017-02-01 14:00:00      1.0  1.626175e+09   234970.0         0.0
2017-02-01 14:15:00      1.0 -1.829051e+09   354830.0         0.0
2017-02-01 14:30:00      1.0  1.228671e+08   915080.0         0.0
2017-02-01 14:45:00      1.0  9.494441e+08   328610.0         0.0
2017-02-01 15:00:00      1.0  1.613980e+09   192680.0         0.0
2017-02-01 15:15:00      1.0 -2.102657e+09   203270.0         0.0
2017-02-01 15:30:00      1.0 -2.239922e+08   862360.0         0.0
2017-02-01 15:45:00      1.0 -2.105889e+09   996140.0         0.0
2017-02-01 16:00:00      1.0  5.725466e+08  1178900.0         0.0
2017-02-01 16:15:00      1.0 -8.429747e+08  1164210.0         0.0
2017-02-01 16:30:00      1.0  1.796521e+09  1122660.0         0.0
2017-02-01 16:45:00      1.0 -2.011012e+09  3225600.0         0.0
2017-02-01 17:00:00      1.0  1.773578e+09  1277890.0         0.0
2017-02-01 17:15:00      1.0 -5.474506e+08   375970.0         0.0
2017-02-01 17:30:00      1.0  3.821834e+08   197060.0         0.0
2017-02-01 17:45:00      1.0  1.966467e+09   906080.0         0.0
2017-02-01 18:00:00      1.0 -1.522868e+09   337830.0         0.0
2017-02-01 18:15:00      1.0  3.523807e+07   348850.0         0.0

[58410 rows x 4 columns]

In [139]:
print(len(temp_df))
# 30 minute resample
new = temp_df.head(1000).resample('30T').first()
print(len(new))
print(new.dtypes)

1000000
28095
METERID       float64
ENERGY        float64
POWER_ALL     float64
ENERGY_OUT    float64
dtype: object

In [134]:
new_df = pd.DataFrame()
df_iter = get_df_iter()

for i in range(100):
    temp_df = df_iter.get_chunk()
    temp_df = temp_df.pipe(lambda x: x[x.METERID == 1])
    #print("chunk",i)
    pd.concat([new_df,temp_df])
    print("chunk",i, len(temp_df),'rows added')
    break
    #new_df.concat(temp_df)

chunk 0 1000000 rows added

In [135]:
temp_df.dtypes

METERID       int32
ENERGY        int32
POWER_ALL     int32
ENERGY_OUT    int32
dtype: object

In [ ]:
dfs = [] # this list will store the filtered dataframes for concatenation


    # filter

# combine filtered dfs into large output df
concat_df = pd.concat(dfs)

In [45]:
#df = pd.read_csv(this_file, nrows=100,delimiter=";",header=None)

In [46]:
#df.tail()

    0                    1           2       3      4      5       6  7   8
95  1  2015-06-04 08:11:34  3887162000  307140  84710  90980  131450  0 NaN
96  1  2015-06-04 08:11:36  3888848000  299490  77070  90920  131500  0 NaN
97  1  2015-06-04 08:11:38  3890564000  311500  89600  90490  131410  0 NaN
98  1  2015-06-04 08:11:40  3892221000  294830  73410  90000  131420  0 NaN
99  1  2015-06-04 08:11:42  3893938000  313330  91820  89740  131770  0 NaN

In [ ]:
# columns we wish to keep/filter on
#cols_to_keep = [‘id’, ‘member_id’, ‘loan_amnt’, ‘funded_amnt’]

In [ ]:
#for i,chunk in enumerate(pd.read_csv('bigfile.csv', chunksize=500000)):
#    chunk.to_csv('chunk{}.csv'.format(i))